# s3.tf Private S3 bucket for ticket PDFs generated by PdfService.java.

resource "aws_s3_bucket" "ticket_pdfs" {
  bucket        = var.s3_bucket_name
  force_destroy = true

  tags = merge(local.common_tags, { Name = "${var.project_name}-ticket-pdfs" })
}

resource "aws_s3_bucket_public_access_block" "ticket_pdfs" {
  bucket                  = aws_s3_bucket.ticket_pdfs.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "ticket_pdfs" {
  bucket = aws_s3_bucket.ticket_pdfs.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "ticket_pdfs" {
  bucket = aws_s3_bucket.ticket_pdfs.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "ticket_pdfs" {
  bucket = aws_s3_bucket.ticket_pdfs.id

  # Now that versioning is enabled, every overwrite/delete keeps the prior version instead of removing data —

  rule {
    id     = "expire-old-tickets"
    status = "Enabled"

    filter { prefix = "tickets/" }

    expiration { days = 365 }
    noncurrent_version_expiration { noncurrent_days = 90 }
  }

  rule {
    id     = "expire-old-cancellation-invoices"
    status = "Enabled"

    filter { prefix = "cancellations/" }

    expiration { days = 365 }
    noncurrent_version_expiration { noncurrent_days = 90 }
  }

  rule {
    id     = "expire-old-event-images"
    status = "Enabled"

    # Event images: keep for 3 years.
    filter { prefix = "events/images/" }

    expiration { days = 1095 }
    noncurrent_version_expiration { noncurrent_days = 90 }
  }
}
