# =============================================================
#  s3.tf
#
#  Private S3 bucket for ticket PDFs generated by PdfService.java.
#  S3Config.java uses IAM role credentials (AWS_ACCESS_KEY_ID is
#  blank in .env → SDK falls back to EC2 instance role).
#
#  application.properties:
#    aws.s3.bucket = ${S3_BUCKET_NAME}
#    aws.region    = ${AWS_REGION}
# =============================================================

resource "aws_s3_bucket" "ticket_pdfs" {
  bucket        = var.s3_bucket_name
  force_destroy = true

  tags = { Name = "${var.project_name}-ticket-pdfs" }
}

resource "aws_s3_bucket_public_access_block" "ticket_pdfs" {
  bucket                  = aws_s3_bucket.ticket_pdfs.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "ticket_pdfs" {
  bucket = aws_s3_bucket.ticket_pdfs.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "ticket_pdfs" {
  bucket = aws_s3_bucket.ticket_pdfs.id

  rule {
    id     = "expire-old-tickets"
    status = "Enabled"

    filter { prefix = "tickets/" }

    expiration { days = 365 }
  }
}
